"""initial_schema

Revision ID: 001
Revises: 
Create Date: 2026-06-04 00:02:35.651081

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('experiencia_anos', sa.Float(), nullable=False),
    sa.Column('habilidades', sa.Text(), nullable=False),
    sa.Column('curriculo_texto', sa.Text(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatos_id'), 'candidatos', ['id'], unique=False)
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('contato', sa.String(length=160), nullable=False),
    sa.Column('media_atraso_dias', sa.Float(), nullable=False),
    sa.Column('taxa_atraso', sa.Float(), nullable=False),
    sa.Column('total_pedidos', sa.Integer(), nullable=False),
    sa.Column('desvio_atraso_dias', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('endereco', sa.String(length=220), nullable=False),
    sa.Column('status', sa.Enum('planejada', 'em_andamento', 'concluida', 'pausada', name='statusobra'), nullable=False),
    sa.Column('prioridade', sa.Enum('alta', 'media', 'baixa', name='prioridade'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_id'), 'obras', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('gestor', 'operador', 'rh', name='perfilusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('tipo_obra', sa.String(length=120), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=False),
    sa.Column('habilidades', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('aberta', 'pausada', 'encerrada', name='statusvaga'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vagas_id'), 'vagas', ['id'], unique=False)
    op.create_table('historico_entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('dias_atraso', sa.Integer(), nullable=False),
    sa.Column('tipo_insumo', sa.String(length=100), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_entregas_id'), 'historico_entregas', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_real_entrega', sa.Date(), nullable=True),
    sa.Column('tipo_insumo', sa.String(length=100), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('prioridade', sa.Enum('alta', 'media', 'baixa', name='prioridade'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'entregue', 'atrasado', name='statuspedido'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('prob_atraso', sa.Float(), nullable=False),
    sa.Column('nivel_alerta', sa.Enum('vermelho', 'amarelo', 'verde', name='nivelalerta'), nullable=False),
    sa.Column('texto_alerta', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_historico_entregas_id'), table_name='historico_entregas')
    op.drop_table('historico_entregas')
    op.drop_index(op.f('ix_vagas_id'), table_name='vagas')
    op.drop_table('vagas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_obras_id'), table_name='obras')
    op.drop_table('obras')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_table('fornecedores')
    op.drop_index(op.f('ix_candidatos_id'), table_name='candidatos')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
