"""check_modularization

Revision ID: adc70d0a3759
Revises: 001
Create Date: 2026-06-07 04:57:58.560084

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc70d0a3759'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidatos', 'curriculo_texto',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('candidatos', 'resumo',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('fornecedores', 'contato',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=180),
               existing_nullable=False)
    op.alter_column('pedidos', 'texto_alerta',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'texto_alerta',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('fornecedores', 'contato',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=160),
               existing_nullable=False)
    op.alter_column('candidatos', 'resumo',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('candidatos', 'curriculo_texto',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
